### ISSUE TITLE
Driver

### ISSUE THREAD

**Issue by dryansweet** [bvarner/pi485#9]
Is there a RasPi driver for this scheme you're using? I'm unable to get the the direction pin working well at the user level.

**Comment by bvarner** [comment]
With this hardware there is no need for software flow control (setting the direction pins) from user-level. You hook up the power and the TX/RX pins to the raspberry pi UART, and off you go.

This is precisely why I implemented flow control in hardware.

My rambling analysis includes complaints about hysteresis in software flow control schemes.
https://github.com/bvarner/pi485#de--re-pin-hysteresis.

For what it's worth, if you search for "UART to RS485 Converter RS485 to TTL Module Precise Module" you'll find some plain circuit board modules on aliexpress and amazon which work _great_ and are far more robust (proper termination, protection, etc.) than my very simplistic schematics here. They also implement hardware flow control.

I've actually switched over to using those. The pi485 stuff was an excellent educational project for myself, though. ;-)

Good luck!
